name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TZ: UTC

jobs:
  ci:
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:ltr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: fix Python command
        run: apt-get install python-is-python3

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install --without gdal

      - name: Rebuild docs
        run: poetry run mkdocs build

      - name: Regenerate plugin repo XML
        run: poetry run pluginadmin --verbose generate-plugin-repo-xml

  publish-docs:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:ltr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: fix Python command
        run: apt-get install python-is-python3

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install pluginadmin dependencies
        run: poetry install --without gdal

      - name: generate plugin repo XML
        run: poetry run pluginadmin --verbose generate-plugin-repo-xml

      - name: update docs
        run: poetry run mkdocs gh-deploy --force
